dist: trusty
language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
  - hhvm-3.18

cache:
  directories:
    - $HOME/.composer/cache/files

before_script:
  - travis_wait 30 composer install --no-interaction

script:
  - composer run check

jobs:
  include:
    - stage: report
      php: 5.6
      script: composer run check
      script: php vendor/bin/php-coveralls -v

sudo: false
